import type { Metadata } from "next";
import { Geist, Permanent_Marker } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const perMarker = Permanent_Marker({
  variable: "--font-permanent-marker",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${perMarker.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
